### ISSUE TITLE
mention all track properties that are drag sources and targets for loading tracks

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#218]
in https://www.mixxx.org/manual/latest/en/chapters/library.html#loading-tracks only `title` is mentioned, but this also applies to artist, album, ... and cover art.

**Comment by ronso0** [comment]
any PR addressing this should be based on https://github.com/mixxxdj/manual/pull/135 in case it's not merged, yet.

**Comment by Goodiec** [comment]
Hello, I would like to work on this. Noticed that the properties that are visible on the deck are the track artist, track title and the track cover. Do you think that since track cover will be mentioned that a brief description of it should be added in the Track Information Display section like you have for track title and track cover[ here ](https://www.mixxx.org/manual/latest/en/chapters/user_interface.html#interface-track-info)?

**Comment by ronso0** [comment]
Yes, that would be nice.
For the description, take a look at the tooltips that are displayed when hovering the cover.
The strins are set in https://github.com/mixxxdj/mixxx/blob/2.3/src/skin/tooltips.cpp#L798 (see also the `dropTracksHere` and `dragItem` appendixes set above that)

**Comment by Goodiec** [comment]
Here's a [pull request](https://github.com/mixxxdj/manual/pull/234) for this. Haven't added a description for the cover art in the Track Information Display section as I noticed the images would have to be updated also to include cover art as it is now in the software. Kindly let me know how you think I should go about that. Thank you

**Comment by Goodiec** [comment]
Couldn't get the previous request to pass so I created a new one, please review - https://github.com/mixxxdj/manual/pull/241
