### ISSUE TITLE
document how AutoDJ relies on crossfader assignment

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#679]
Let's document the crossfader assignment conditions/issue in https://manual.mixxx.org/2.4/en/chapters/djing_with_mixxx#auto-dj 

E.g. AutoDJ needs a "left" and a "right" deck.
AutoDJ uses decks 3/4 if deck 1 and/or 2 are not assigned to the left and right side of the crossfader.

https://mixxx.discourse.group/t/disabling-all-but-2-decks-for-autodj/26932/11

**Comment by Eve00000** [comment]
Something like this?

12.8. Auto DJ
Auto DJ is the automatic Mixxx player engine. It automatically loads tracks in the decks and mixes them automatically.
Auto DJ needs tracks, these tracks can be manually selected on track level, on crate level or automatic from the library, read more below. 

To be able to mix the tracks Auto DJ takes control of the crossfader. See [crossfader](https://manual.mixxx.org/2.4/en/chapters/user_interface.html#crossfader).
Auto DJ requires the allocation of at least 1 deck to each side of the crossfader. The assignement of the decks is done by the orientation-knobs. Each deck can be orientated to the left side, right side or center of the crossfader. If a deck's orientation is centered, the crossfader can't affect it.
When Auto DJ is toggled on, Auto DJ wil check if deck 1&2 are on a opposed side of the crossfader (not centered), if this is the case, Auto DJ will take control of deck 1 and 2.
If deck 1 & 2 don't have an opposed crossfader orientation, Auto DJ will check the orientation of Deck 3 & 4. If the orientation of these decks matches the requirement, Auto DJ will use these decks, even if these decks aren't visually shown in your Mixxx screen. To show deck 3 & 4, you can toggle the 4 Decks-button on top in the user interface or in the skin settings
See [skin settings](https://manual.mixxx.org/2.4/en/chapters/user_interface.html#crossfader).
The crossfader indicates which deck is playing and moves to the other side during the transition to the new track.
When you toggle 'off' the Auto DJ, the crossfader will stay on it's last position. 
Since version 2.4.... you can choose to reset the crossfader to the centered positionafter disabling AUTO DJ by selecting the option 'reset crossfader to center after disabling Auto DJ' in the preferences. See [crossfader](https://manual.mixxx.org/2.4/en/chapters/user_interface.html#crossfader](https://manual.mixxx.org/2.4/en/chapters/preferences).
If Auto DJ is enabled, you can see a colored rectangule around the crossfader.

**Comment by ronso0** [comment]
Thank you for this proposal.

 > When Auto DJ is toggled on, Auto DJ wil check if deck 1&2 are on a opposed side of the crossfader (not centered), if this is the case, Auto DJ will take control of deck 1 and 2.
If deck 1 & 2 don't have an opposed crossfader orientation, Auto DJ will check the orientation of Deck 3 & 4.

Not quite. AutoDJ iterates over all decks and picks the first left and the first right deck ,which could also be 3 and 2. Also I think we shouldn't write too much aboue the crossfader, a link to the crossfader section and the GUI assignment buttons would suffice.
IMHO collaboration on text works better in code convos/reviews, do you mind opening a PR?
