### ISSUE TITLE
Relink should be better described

### ISSUE THREAD

**Issue by ghost** [mixxxdj/manual#80]
The **library relink function** should be better described. I used it to set up a training instance on a second machine and was not certain how and after which user interaction it worked, even after reading all manual content about it.

A typical scenario is, that a harddisc is defect and the user sets up a new machine with a different library path. A step by step howto to set it up with backups of music dir and mixxx dir would be great. Keep in mind, this is a critical situation, the DJ can loose a lot of his work, when playlists and crates are not usable any more. (Analyze results the same). _This would be a worst case user experience, so the manual should be more explicit here_.

What I miss:

- Does the relink require a select of one library path before (even if only one library path exist)
- When does the relink happen? When I press apply in options dialog or during the next library scan? When can I see it in the location column of the playlists for prove?
- Which parts of the library are touched by the relink (playlists, crates, missing tracks, analyze results). How to prove?
- In my experience, during the next library scan after relink, mixxx takes a lot of time a one track with a path from the old location. At this moment the program seems to be stalled (my lib is large), and I had not enough patience to wait for the first try, killed the process and so the relink. Only after a full run of library scan, the relink was successful. Correct?
- _for experts_: what are the SQL steps in the sqlite db to fix it, when relink does not help or the db structure is partly corrupt

**Comment by dharmelolar** [comment]
Hello, please can i work on this issue?

**Comment by Holzhaus** [comment]
@dharmelolar Thanks!

**Comment by Goodiec** [comment]
@dharmelolar are you still working on this?

**Comment by ronso0** [comment]
@Goodiec 
I think you can go ahead and open a PR for this, though I don't really consider this a starter bug.
For best results this requires actual testing of file/folder relinking. This may be rather time consuming as you need to set up a library first incl. a few crates and playlists, then simulate the enire file moving and relinking, then double check if your crates & playlists are (re-)populated correctly. Also a contributor with knowledge about the database and related transactions needs to assist for the details/caveats.

**Comment by Goodiec** [comment]
> I think @uklotzde could judge best if this is feasible.

Ok, thank you!

**Comment by uklotzde** [comment]
I also recommend the approach @ronso0 suggested:

1st phase: Prepare a fresh Mixxx profile
- Create a music folder and populate it with some audio files of various formats, both in the top-level root folder and in subfolders
- Start Mixxx with a new profile and select the top-level music folder
- Analyze all tracks
- Load tracks and set cue points
- Create playlists and crates and populate them with tracks from the music folder
- Play some tracks to implicitly populate one or more *History* playlists
- Restart Mixxx and check that everything is there
- Close Mixxx
- Backup the Mixxx profile folder

2nd phase: Prepare the relink test
- Rename the music folder or move it to another volume/drive

3nd phase: Test relinking
- Restore the saved Mixxx profile from the backup (has to be repeated before each test procedure)
- Start Mixxx
- Optionally: Rescan the library -> all tracks become missing (*)
- Relink the music folder to the new location
- Rescan the library (known issue: https://bugs.launchpad.net/mixxx/+bug/1862396)
- Verify that no tracks are missing
- Verify that no tracks are duplicated
- Check that the file path in the *location* column only points to the new music folder
- Verify that tracks can be loaded and played
- Verify that cue points in tracks have been preserved
- Verify that no tracks are missing from crates and playlists (including *History*)
- Verify that tracks are not re-analyzed, i.e. that the cached analysis results are reused

(*) If you rescan the library before relinking then all tracks will go into *Missing*. We have to test both cases, because Mixxx can be configured to automatically rescan the library on startup before you have the chance to perform the relinking.

Document the steps that worked. Report any issues that you encounter, e.g. if tracks disappear from playlists or crates. Those bugs must be fixed to prevent data loss! We might not be aware of them yet.

**Comment by Goodiec** [comment]
> I also recommend the approach @ronso0 suggested:
> 
> 1st phase: Prepare a fresh Mixxx profile
> 
> * Create a music folder and populate it with some audio files of various formats, both in the top-level root folder and in subfolders
> * Start Mixxx with a new profile and select the top-level music folder (https://github.com/mixxxdj/mixxx/wiki/Troubleshooting#starting-with-a-new-configuration)
> * Analyze all tracks
> * Load tracks and set cue points
> * Create playlists and crates and populate them with tracks from the music folder
> * Play some tracks to implicitly populate one or more _History_ playlists
> * Restart Mixxx and check that everything is there
> * Close Mixxx
> * Backup the Mixxx profile folder
> 
> 2nd phase: Prepare the relink test
> 
> * Rename the music folder or move it to another volume/drive
> 
> 3nd phase: Test relinking
> 
> * Restore the saved Mixxx profile from the backup (has to be repeated before each test procedure)
> * Start Mixxx
> * Optionally: Rescan the library -> all tracks become missing (*)
> * Relink the music folder to the new location
> * Rescan the library (known issue: https://bugs.launchpad.net/mixxx/+bug/1862396)
> * Verify that no tracks are missing
> * Verify that no tracks are duplicated
> * Check that the file path in the _location_ column only points to the new music folder
> * Verify that tracks can be loaded and played
> * Verify that cue points in tracks have been preserved
> * Verify that no tracks are missing from crates and playlists (including _History_)
> * Verify that tracks are not re-analyzed, i.e. that the cached analysis results are reused
> 
> (*) If you rescan the library before relinking then all tracks will go into _Missing_. We have to test both cases, because Mixxx can be configured to automatically rescan the library on startup before you have the chance to perform the relinking.
> 
> Document the steps that worked. Report any issues that you encounter, e.g. if tracks disappear from playlists or crates. Those bugs must be fixed to prevent data loss! We might not be aware of them yet.

Thanks a lot, will give it a try.

**Comment by Goodiec** [comment]
Created a pull request for this issue [here](https://github.com/mixxxdj/manual/pull/287), kindly review. Thank you
